"""Render: verified items + an editorial plan -> ReleaseNotes (data) -> GitHub Markdown.

The JSON document is built first and the Markdown is rendered *from it*, so the two forms
cannot drift. Rendering is pure: same inputs, byte-identical output (which is what lets the
recorded evals run in CI).

Markdown safety, because this text gets posted as PR comments and release bodies:
  - `@name` is wrapped in backticks so a release note never pings strangers;
  - `<` is escaped so repository text cannot inject HTML;
  - newlines inside a summary are collapsed so one item cannot fake a heading.
"""

from __future__ import annotations

import re

from ..models import (
    SECTION_TITLES,
    CollectedRange,
    DevDraft,
    MergedItem,
    NoteItem,
    ReleaseNotes,
    Section,
    UserDraft,
    Verification,
)
from .verify import (
    budget_intro,
    is_confirmed_breaking,
    is_possibly_breaking,
    make_ref,
    plan_sections,
)

_MENTION = re.compile(r"(?<![\w`])@([A-Za-z0-9][A-Za-z0-9-]{0,38}(?:/[A-Za-z0-9_.-]+)?)")


def md_safe(text: str) -> str:
    text = " ".join(text.split())
    text = text.replace("<", "&lt;")
    return _MENTION.sub(r"`@\1`", text)


def build_notes(
    *,
    audience: str,
    items: list[MergedItem],
    draft: DevDraft | UserDraft,
    collected: CollectedRange,
    verification: Verification,
    prompt_versions: dict[str, str],
    models: dict[str, str],
) -> ReleaseNotes:
    sections: list[Section] = []
    for key, prose, section_items in plan_sections(items, draft, audience, verification):
        notes = [
            NoteItem(
                id=item.id,
                category=item.category,
                summary=item.dev_summary if audience == "dev" else item.user_summary,
                breaking=is_confirmed_breaking(item),
                possibly_breaking=audience == "dev" and is_possibly_breaking(item),
                breaking_confidence=round(item.breaking_confidence, 2),
                migration_note=item.migration_note
                if audience == "dev" or is_confirmed_breaking(item)
                else None,
                refs=[make_ref(collected.repo, ref) for ref in item.refs],
                source=item.source,
            )
            for item in section_items
        ]
        sections.append(Section(category=key, title=SECTION_TITLES[key], prose=prose, items=notes))
    title = (
        f"What's new in {collected.repo} {collected.head}"
        if audience == "user"
        else f"{collected.repo} {collected.base}...{collected.head}"
    )
    return ReleaseNotes(
        audience=audience,  # type: ignore[arg-type]
        repo=collected.repo,
        base=collected.base,
        head=collected.head,
        title=title,
        intro=budget_intro(draft.intro, audience, verification),
        sections=sections,
        compare_url=collected.compare_url,
        commit_count=len(collected.commits),
        prompt_versions=prompt_versions,
        models=models,
    )


def render_markdown(notes: ReleaseNotes) -> str:
    lines = [f"## {md_safe(notes.title)}", ""]
    if notes.intro:
        lines += [md_safe(notes.intro), ""]
    for section in notes.sections:
        lines += [f"### {section.title}", ""]
        if section.prose:
            lines += [md_safe(section.prose), ""]
        for item in section.items:
            links = ", ".join(f"[{ref.id}]({ref.url})" for ref in item.refs)
            confidence = (
                f" (confidence {item.breaking_confidence:.1f})" if item.possibly_breaking else ""
            )
            lines.append(f"- {md_safe(item.summary)}{confidence} ({links})")
            if item.migration_note:
                lines.append(f"  - Migration: {md_safe(item.migration_note)}")
        lines.append("")
    if not notes.sections:
        lines += ["_No changes in this range are relevant to this audience._", ""]
    lines.append(
        f"<sub>Generated by Changelog Forge from {notes.commit_count} commits in "
        f"[{notes.base}...{notes.head}]({notes.compare_url}). Every link was checked against "
        "the commits in this range.</sub>"
    )
    return "\n".join(lines) + "\n"
